Feature testing setup
garden-share-08/garden-share-fe pull request #24
Opened 2021-02-25 00:20 UTC by chadrick-d-dev

#### What does  this PR do?
- Setup of testing files

#### Where should the reviewer start?
- Review files changed

#### How should this be manually tested?
- No testing needed, these are for preparation for testing

#### Any background context you want to provide?
- We needed specific tests for our files

#### What are the relevant tickets?
#23

2021-02-25 16:21 UTC, atownse commented on src/components/Login/Login.test.js
> +describe('Login', () => {
Thank you for setting these up

2021-02-25 16:21 UTC, atownse approved these changes

2021-02-25 18:22 UTC, bruce-gordon requested changes
Thank you for all your great work on this!  I do see two things that should be adjusted before merge:
1. MyOffers.test.js is not currently passing on this branch.  Line 2 (in the import section) should be -- **import Login from '../login/Login';**
2. Inside the "userListing" directory, all of the files start with a lowercase letter.  They should each be "UserListing.js", "UserListing.scss", etc. 

Can you please tweak those two things and then we'll get this merged?  Thank you!

2021-02-25 18:47 UTC, chadrick-d-dev commented
> Thank you for all your great work on this! I do see two things that should be adjusted before merge:
> 
> 1. MyOffers.test.js is not currently passing on this branch.  Line 2 (in the import section) should be -- **import Login from '../login/Login';**
> 2. Inside the "userListing" directory, all of the files start with a lowercase letter.  They should each be "UserListing.js", "UserListing.scss", etc.
> 
> Can you please tweak those two things and then we'll get this merged? Thank you!

Returned them to the way they were. I think the issue was due to the naming being different on main. Our naming convention for files is Camel case with caps at the beginning with folders starting with lower case. So it's just a naming convention discrepancy. I think we could do pull request directly on this repo to resolve the naming.

2021-02-26 18:12 UTC, bruce-gordon approved these changes

2021-02-26 18:12 UTC, merged